### ISSUE TITLE
idea: push transport metadata up

### ISSUE THREAD

**Issue by thinktainer** [uw-labs/substrate#43]
In order to be able to switch a stream from one transport to another, it would be useful to experiment with pushing metadata from the transport up to the messages. This would allow a user to try and reconcile different transports and potentially switch between them. My use case here would be to use s3 streams as a mechanism for being able to quickly catch up to a messaging system transport stream. With the metadata added to the s3 files, one could try to reinstate a connection on the messaging system with information obtained from the metadata, in order to continue normal operation.

**Comment by mjgarton** [comment]
I wonder whether this can be somehow achieved internally without extending the substrate contract at all.  Substrate deliberately exposes a minimum in order to keep usage simple and also make porting to other backends easy and consistent.   I do understand the need for wanting to do something like this.  Perhaps a good was is to fork and experiment a bit with different options before coming back with some concrete proposals around the one(s) that worked out best (without compromising the design goals of substrate)?

**Comment by charlie** [comment]
@thinktainer What information in the metadata would affect the way in which one reconnects to the messaging backend, and how would it affect it? (As usual I need concrete details to understand the problem...)
